version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: easypasswordwillruinyou
      MYSQL_USER: aisudbqaasd
      MYSQL_PASSWORD: alsoeasypassword
      MYSQL_DATABASE: undangan-db
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --performance_schema=0
  undangan-api:
    restart: always
    build: .
    environment:
      DB_HOST: mysql
      DB_USER: aisudbqaasd
      DB_PASS: alsoeasypassword
      DB_NAME: undangan-db
      DB_PORT: 3306
      DB_DRIV: mysql
    ports:
      - 8181:80
